name: GitHub
on:
  push:
    tags: ["*"]

jobs:
  release:
    permissions: write-all
    runs-on: "ubuntu-latest"
    name: Create a Release
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/checkout@v4
      - name: Create a new GitHub release
        run: gh release create ${{ github.ref_name }} -p --notes-from-tag

